config/routes.rb
Steep::Application.routes.draw do

  resources :posts

  
  resources :teas do
    get 'search'
    resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :posts
  end 
  
  resources :tea_types do
  end
  match '/teas/search' => 'teas#search', :as => "search"
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/auth/:provider/callback" => "sessions#new"  

  root :to => 'home#index'

end

app/controllers/tea_types_controller.rb
class TeaTypesController < ApplicationController
  # GET /tea_types
  # GET /tea_types.json
  def index
    @tea_types = TeaType.all
  
  end

  # GET /tea_types/1
  # GET /tea_types/1.json
  def show
    @teatype = TeaType.find(params[:id])
    @teas = @teatype.teas

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tea_type }
    end
  end

  # GET /tea_types/new
  # GET /tea_types/new.json
  def new
    @tea_type = TeaType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tea_type }
    end
  end

  # GET /tea_types/1/edit
  def edit
    @tea_type = TeaType.find(params[:id])
  end

  # POST /tea_types
  # POST /tea_types.json
  def create
    @tea_type = TeaType.new(params[:tea_type])

    respond_to do |format|
      if @tea_type.save
        format.html { redirect_to @tea_type, notice: 'Tea type was successfully created.' }
        format.json { render json: @tea_type, status: :created, location: @tea_type }
      else
        format.html { render action: "new" }
        format.json { render json: @tea_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tea_types/1
  # PUT /tea_types/1.json
  def update
    @tea_type = TeaType.find(params[:id])

    respond_to do |format|
      if @tea_type.update_attributes(params[:tea_type])
        format.html { redirect_to @tea_type, notice: 'Tea type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tea_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tea_types/1
  # DELETE /tea_types/1.json
  def destroy
    @tea_type = TeaType.find(params[:id])
    @tea_type.destroy

    respond_to do |format|
      format.html { redirect_to tea_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tea_types_helper.rb
module TeaTypesHelper
end

app/views/tea_types/_form.html.erb
<%= form_for(@tea_type) do |f| %>
  <% if @tea_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tea_type.errors.count, "error") %> prohibited this tea_type from being saved:</h2>

      <ul>
      <% @tea_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :repTea %><br />
    <%= f.text_area :repTea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tea_types/edit.html.erb
<h1>Editing tea_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @tea_type %> |
<%= link_to 'Back', tea_types_path %>

app/views/tea_types/index.html.erb
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Teas</title>
<style type="text/css">
body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
	/*margin: 0 auto auto 0;*/
}


#login { 
  position:absolute;
	width:197px;
	height:212px;
	z-index:1;
	left: 1274px;
	top: -7px;
    /*margin: 0px 1000px 200px 0px;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

#signup {
  position:absolute;
	width:223px;
	height:239px;
	z-index:2;
	left: 1415px;
	top: -15px;
  
	/*width: 15%;*/
    /*height: 350px;*/
}

#bigoolong {
  position:absolute;
  background: url(<%= asset_path ('big' + @teatype.image) %>) no-repeat scroll 0 0;
	width:454px;
	height:559px;
	z-index:3;
	left: 275px;
	top: -117px;
	
}	

#paperbox {
  position:absolute;
  background: url(<%= asset_path 'paperbox.png' %>) no-repeat scroll 0 0;
	width:784px;
	height:567px;
	z-index:4;
	left: 725px;
	top: -94px;
}	

#like {
  position:absolute;
  background: url(<%= asset_path 'like.png' %>) no-repeat scroll 0 0;
	width:200px;
	height:115px;
	z-index:1;
	left: 506px;
	top: 431px;
}

#credits {
  position:absolute;
  background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#txt{
  position:absolute;
  left:100px;
  top:70px;
  height:350px;
  width:600px;
  z-index:5;
  overflow:auto;
}

</style>
</head>

<body>
<!--<img src="images/background.png" width="4800" height="3600" />-->
<div class="header">
<div id="title">
     </div><!--end title-->
     
<% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div>
<div id="main">

  <div id="credits"></div>
  <div id="bigoolong"></div>
  <div id="paperbox">  <div id = "txt">  
   <table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Reptea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tea_types.each do |tea_type| %>
  <tr>
    <td><%= tea_type.name %></td>
    <td><%= tea_type.image %></td>
    <td><%= tea_type.repTea %></td>
    <td><%= link_to 'Show', tea_type %></td>
    <td><%= link_to 'Edit', edit_tea_type_path(tea_type) %></td>
    <td><%= link_to 'Destroy', tea_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>



<br />
</div>
    
    <div id="like"></div>
  </div>
</div>
</body>
</html>

app/views/tea_types/new.html.erb
<h1>New tea_type</h1>

<%= render 'form' %>

<%= link_to 'Back', tea_types_path %>

app/views/tea_types/show.html.erb
  
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Teas</title>
<style type="text/css">
body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
	/*margin: 0 auto auto 0;*/
}

#title {
  background: url(<%= asset_path @teatype.title %>) no-repeat scroll 0 0;
	/*margin: 0 1000px 1000px 0;*/
	margin: 0px 650px;
	width: 40%;
	height:350px;
}

#login { 
  position:absolute;
	width:197px;
	height:212px;
	z-index:1;
	left: 1274px;
	top: -7px;
    /*margin: 0px 1000px 200px 0px;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

#signup {
  position:absolute;
	width:223px;
	height:239px;
	z-index:2;
	left: 1415px;
	top: -15px;
  
	/*width: 15%;*/
    /*height: 350px;*/
}

#bigoolong {
  position:absolute;
  background: url(<%= asset_path ('big' + @teatype.image) %>) no-repeat scroll 0 0;
	width:454px;
	height:559px;
	z-index:3;
	left: 275px;
	top: -117px;
	
}	

#paperbox {
  position:absolute;
  background: url(<%= asset_path 'paperbox.png' %>) no-repeat scroll 0 0;
	width:784px;
	height:567px;
	z-index:4;
	left: 725px;
	top: -94px;
}	

#like {
  position:absolute;
  background: url(<%= asset_path 'like.png' %>) no-repeat scroll 0 0;
	width:200px;
	height:115px;
	z-index:1;
	left: 506px;
	top: 431px;
}

#credits {
  position:absolute;
  background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#txt{
  position:absolute;
  left:100px;
  top:70px;
  height:455px;
  width:600px;
  z-index:5;
  overflow:auto;
}

#home {
  position:absolute;
  top:20px;
  left:20px;
}

</style>
</head>

<body>
<!--<img src="images/background.png" width="4800" height="3600" />-->
<div class="header">
<div id="title">
     </div><!--end title-->
     
<% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div>
<div id="main">

  <div id="credits"></div>
  <div id="bigoolong"></div>
  <div id="paperbox">  <div id = "txt">  
    <table>
      <tr>
        <td><h3> Tea </h3></td>
        <td><h3> Region </h3></td>
      </tr>
          <% @teatype.teas.each do |tea| %>
  <tr>
<h3><td><%= tea.name %></td></h3>
    <td>&nbsp;&nbsp;&nbsp;<%=tea.region%> </td>
    <% if signed_in? %>
    <td><%= link_to image_tag("/assets/likesmall.png"), tea_likes_path(tea, @tea_type), method: :post%></td>
    <td><%= tea.likes.count('user_id', :distinct => true) %> Users like this tea</td>
    <%else%>
    <td><%= tea.likes.count('user_id', :distinct => true) %> Users like this tea</td>
    <td>&nbsp;&nbsp;&nbsp;<%= link_to 'log in', signin_path%> to 'like' this tea </td>
    <%end%>
 </tr>
<% end %>
</table>
<br />
</div>
  </div>
</div>

<div id="home">
    <%= link_to image_tag("/assets/hometab.png", :border=>0), root_path%>
  
  </div>
</body>
</html>