config/routes.rb
Steep::Application.routes.draw do

  resources :posts

  
  resources :teas do
    get 'search'
    resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :posts
  end 
  
  resources :tea_types do
  end
  match '/teas/search' => 'teas#search', :as => "search"
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/auth/:provider/callback" => "sessions#new"  

  root :to => 'home#index'

end

app/models/tea.rb
class Tea < ActiveRecord::Base


  def thumbnail
    "http://api.freebase.com/api/trans/image_thumb" + image_id
  end
  
  def self.search(search)
  if search
    find(:all, :conditions => ['name || region LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
  
end
  belongs_to :tea_type
  has_many :likes
end

app/models/tea_type.rb
class TeaType < ActiveRecord::Base
  has_many :teas

end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
  # GET /teas
  # GET /teas.json
  def index
      @teas = Tea.search(params[:search])
      redirect_to(:back)
 end

def search 
  @teas = Tea.search(params[:search])
end
        #@teas = Tea.search(params[:search]) 
  # GET /teas/1
  # GET /teas/1.json
    def show
    @teas = Tea.search(params[:search])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tea }
    end
  end

 
  # DELETE /teas/1
  # DELETE /teas/1.json
  def destroy
    @tea = Tea.find(params[:id])
    @tea.destroy

    respond_to do |format|
      format.html { redirect_to teas_url }
      format.json { head :no_content }
    end
  end
  

end

app/helpers/teas_helper.rb
module TeasHelper
end

app/views/teas/_form.html.erb
<%= form_for(@tea) do |f| %>
  <% if @tea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tea.errors.count, "error") %> prohibited this tea from being saved:</h2>

      <ul>
      <% @tea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>

  <div class="field">
    <%= f.label :teaType %><br />
    <%= f.text_field :teaType %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teas/edit.html.erb
<h1>Editing tea</h1>

<%= render 'form' %>

<%= link_to 'Show', @tea %> |
<%= link_to 'Back', teas_path %>

app/views/teas/index.html.erb
  
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Teas</title>
<style type="text/css">
body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
	/*margin: 0 auto auto 0;*/
}



#login { 
  position:absolute;
	width:197px;
	height:212px;
	z-index:1;
	left: 1274px;
	top: -7px;
    /*margin: 0px 1000px 200px 0px;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

#signup {
  position:absolute;
	width:223px;
	height:239px;
	z-index:2;
	left: 1415px;
	top: -15px;
  
	/*width: 15%;*/
    /*height: 350px;*/
}


#paperbox {
  position:absolute;
  background: url(<%= asset_path 'paperbox.png' %>) no-repeat scroll 0 0;
	width:784px;
	height:567px;
	z-index:4;
	left: 500px;
	top: -200px;
}	


#credits {
  position:absolute;
  background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#txt{
  position:absolute;
  left:80px;
  top:80px;
  height:400px;
  width:600px;
  z-index:5;
  overflow:auto;
}

</style>
</head>

<body>
<!--<img src="images/background.png" width="4800" height="3600" />-->
<div class="header">
<div id="title">
     </div><!--end title-->
     
<% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div>
<div id="main">

  <div id="credits"></div>
  <div id="bigoolong"></div>
  <div id="paperbox">  <div id = "txt">  
    <h1>Results</h1>
<table>
  <tr>
    <th>Blah</th>
    <th>Name</th>
    <th>Region</th>
    <th>Teatype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teas.each do |tea| %>
  <tr>
    <td><%= tea.name %></td>
    <td><%= tea.region %></td>
    <td><%= link_to tea.tea_type.name, tea.tea_type %></td>
    <% if signed_in? %>
    <td><%= link_to image_tag("/assets/likesmall.png"), tea_likes_path(tea), method: :post%></td>
    <td><%= tea.likes.count %> Users like this tea</td>
    <%else%>
    <td><%= tea.likes.count %> Users like this tea</td>
    <td>&nbsp;&nbsp;<%= link_to 'log in', signin_path%> to 'like' this tea </td>
    <%end%>

  </tr>
<% end %>
</table>



<br />
</div>
    
    <div id="like"></div>
  </div>
</div>
</body>
</html>

app/views/teas/new.html.erb
<h1>New tea</h1>

<%= render 'form' %>

<%= link_to 'Back', teas_path %>

app/views/teas/search.html.erb
  
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Teas</title>
<style type="text/css">
body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
	/*margin: 0 auto auto 0;*/
}



#login { 
  position:absolute;
	width:197px;
	height:212px;
	z-index:1;
	left: 1274px;
	top: -7px;
    /*margin: 0px 1000px 200px 0px;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

#signup {
  position:absolute;
	width:223px;
	height:239px;
	z-index:2;
	left: 1415px;
	top: -15px;
  
	/*width: 15%;*/
    /*height: 350px;*/
}


#paperbox {
  position:absolute;
  background: url(<%= asset_path 'paperbox.png' %>) no-repeat scroll 0 0;
	width:784px;
	height:567px;
	z-index:4;
	left: 500px;
	top: -200px;
}	


#credits {
  position:absolute;
  background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#txt{
  position:absolute;
  left:80px;
  top:80px;
  height:400px;
  width:600px;
  z-index:5;
  overflow:auto;
}

</style>
</head>

<body>
<!--<img src="images/background.png" width="4800" height="3600" />-->
<div class="header">
<div id="title">
     </div><!--end title-->
     
<% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div>
<div id="main">

  <div id="credits"></div>
  <div id="bigoolong"></div>
  <div id="paperbox">  <div id = "txt">  
    <h1>Results</h1>
<table>
  <tr>
    
    <th>Name</th>
    <th>Region</th>
    <th>Teatype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teas.each do |tea| %>
  <tr>
    <td><%= tea.name %></td>
    <td><%= tea.region %></td>
    <% if signed_in? %>
    <td><%= link_to image_tag("/assets/likesmall.png"), tea_likes_path(tea), method: :post%></td>
    <td><%= tea.likes.count %> Users like this tea</td>
    <%else%>
    <td><%= tea.likes.count %> Users like this tea</td>
    <td>&nbsp;&nbsp;<%= link_to 'log in', signin_path%> to 'like' this tea </td>
    <%end%>

  </tr>
<% end %>
</table>



<br />
</div>
    
    <div id="like"></div>
  </div>
</div>
</body>
</html>

app/views/teas/show.html.erb
  
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Teas</title>
<style type="text/css">
body {
  font-family: PTSansRegular;
  margin: 0;
  padding: 0;
  border: 0;
  outline: 0;
  font-size: 100%;
  line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
}


#login { 
  position:absolute;
	width:197px;
	height:212px;
	z-index:1;
	left: 1274px;
	top: -7px;
}

#signup {
  position:absolute;
	width:223px;
	height:239px;
	z-index:2;
	left: 1415px;
	top: -15px;
}


#paperbox {
  position:absolute;
  background: url(<%= asset_path 'paperbox.png' %>) no-repeat scroll 0 0;
	width:784px;
	height:567px;
	z-index:4;
	left: 500px;
	top: -200px;
}	


#credits {
  position:absolute;
  background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#txt{
  position:absolute;
  left:80px;
  top:80px;
  height:400px;
  width:600px;
  z-index:5;
  overflow:auto;
}

#home {
  position:absolute;
  top:20px;
  left:20px;
}

</style>
</head>

<body>
<!--<img src="images/background.png" width="4800" height="3600" />-->
<div class="header">
<div id="title">
     </div><!--end title-->
     
<% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div>
<div id="main">

  <div id="credits"></div>
  <div id="bigoolong"></div>
  <div id="paperbox">  <div id = "txt">  
    <h1>Results</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Region</th>
    <th>Teatype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teas.each do |tea| %>
  <tr>
    <td><%= tea.name %></td>
    <td><%= tea.region %></td>
    <td><%= link_to tea.tea_type.name, tea.tea_type %></td>
    <% if signed_in? %>
    <td><%= link_to image_tag("/assets/likesmall.png"), tea_likes_path(tea), method: :post%></td>
    <td><%= tea.likes.count %> Users like this tea</td>
    <%else%>
    <td><%= tea.likes.count %> Users like this tea</td>
    <td>&nbsp;&nbsp;<%= link_to 'log in', signin_path%> to 'like' this tea </td>
    <%end%>

  </tr>
<% end %>
</table>



<br />
</div>
    
    <div id="like"></div>
  </div>
</div>

<div id="home">
    <%= link_to image_tag("/assets/hometab.png", :border=>0), root_path%>
  
  </div>
</body>
</html>