config/routes.rb
Steep::Application.routes.draw do

  resources :posts

  
  resources :teas do
    get 'search'
    resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :posts
  end 
  
  resources :tea_types do
  end
  match '/teas/search' => 'teas#search', :as => "search"
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/auth/:provider/callback" => "sessions#new"  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :tea, :teaType, :description, :image



has_secure_password
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  belongs_to :tea
  belongs_to :tea_type
  has_many :posts

  has_many :likes
  has_many :teas, :through => :likes
  
  
  def self.search(search)
    if search
      find(:all, :conditions => ['name || email LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  
 #before_filter :authenticate, :except => [:index, :show]
  def index
    @users = User.search(params[:search])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @tea = Tea
    @user = User.find(params[:id])
    @post = @user.posts.build()
    @posts = @user.posts
    @likes = @user.likes
    @teas=@user.teas
    @rand = @teas.find :first, :offset => ( @teas.count * rand ).to_i
    if (@rand != nil)
      @randtype = @rand.tea_type
      @randtea = Tea.where('tea_type_id =?' , @randtype)
      @rtea = @randtea.find :first, :offset => ( @randtea.count * rand ).to_i
      
    end
      
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
      
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

private

    def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

#def authenticate
#authenticate_or_request_with_http_basic do |name, password|
#name == "admin" && password == "secret"
#end

#end

app/helpers/users_helper.rb
module UsersHelper
     # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 325})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.jpg?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def thumbnail_for(user, options = {size: 75})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.jpg?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Steep - An App for All Things Tea</title>

<style type="text/css">


body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
	/*margin: 0 auto auto 0;*/
}

.form {
  position:absolute;
	z-index:1;
	/*left: 327px;*/
  left: 150px;
	top: 30px;
  text-align: center;
  
}

#burlap {
  position:absolute;  
  width: 525px;
  height: 900px;
	z-index: 0;
  left: 525px;
	top: 30px;
     background-image: url(<%= asset_path 'blankburlap.png' %>);
}

#login { 
	/*<background: url(<%= asset_path 'logintab.png' %>) no-repeat scroll 0 0;*/
    /*margin: 0px 1000px 200px 0px;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

#signup {
	/*background: url(<%= asset_path 'signuptab.png' %>) no-repeat scroll 0 0;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

.container {
    width: 1920px;
	height: auto;
} 

#credits {
	background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
}	
#login {
	position:absolute;
	width:278px;
	height:217px;
	z-index:1;
	left: 1274px;
	top: -6px;
}
#signup {
	position:absolute;
	width:216px;
	height:244px;
	z-index:2;
	left: 1415px;
	top: -14px;
}
#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#credits {
	position:absolute;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#error_explanation {
  position: absolute;
  top: 350px;
  left: 1100px;

  color:#f00;
  ul {
    list-style: none;
    margin: 0 0 18px 0;
  }
}

#title1 {
  
}

.field_with_errors {
  @extend .control-group;
  @extend .error;
 }

</style>
</head>

<%= form_for(@user) do |f| %>
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <body>
  <div class="header">

    

  <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), users_path%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div> <!--end signup-->

</div>
  <div class="container">
  </div>
  <div id="burlap">
  <div class="form">
    <div id="title1">
   <h1> Sign Up </h1>
    </div>
<form class="well">
  <div class="field">
    <%= f.text_field :name, :placeholder => @user.name %>
  </div>
  <div class="field">
    <%= f.text_field :email, :placeholder => @user.email %>
  </div>
  <div class="field">
    <%= f.password_field :password, :placeholder => 'enter or change password' %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :placeholder => 'confirm password' %>
  </div>
  <div class="field">
    <%= f.text_area :description, :placeholder =>"tell us a little bit about yourself","cols" => 20, "rows" => 30 %>
  </div>
  
  </form>

 
  <div class="actions">
    <%= f.submit class: 'btn-large btn-inverse' %>
  </div>
</div>
</div>
  <div id="main">
  <div id="credits"></div>
</div>

</body>
<% end %>

app/views/users/_form.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Steep - An App for All Things Tea</title>

<style type="text/css">


body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
	/*margin: 0 auto auto 0;*/
}

.form {
  position:absolute;
	z-index:1;
	/*left: 327px;*/
  left: 150px;
	top: 30px;
  text-align: center;
  
}

#burlap {
  position:absolute;  
  width: 525px;
  height: 900px;
	z-index: 0;
  left: 525px;
	top: 30px;
     background-image: url(<%= asset_path 'blankburlap.png' %>);
}

#login { 
	/*<background: url(<%= asset_path 'logintab.png' %>) no-repeat scroll 0 0;*/
    /*margin: 0px 1000px 200px 0px;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

#signup {
	/*background: url(<%= asset_path 'signuptab.png' %>) no-repeat scroll 0 0;*/
	/*width: 15%;*/
    /*height: 350px;*/
}

.container {
    width: 1920px;
	height: auto;
} 

#credits {
	background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
}	
#login {
	position:absolute;
	width:278px;
	height:217px;
	z-index:1;
	left: 1274px;
	top: -6px;
}
#signup {
	position:absolute;
	width:216px;
	height:244px;
	z-index:2;
	left: 1415px;
	top: -14px;
}
#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#credits {
	position:absolute;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}

#error_explanation {
  position: absolute;
  top: 350px;
  left: 1100px;

  color:#f00;
  ul {
    list-style: none;
    margin: 0 0 18px 0;
  }
}

#title1 {
  
}
.field_with_errors {
  @extend .control-group;
  @extend .error;
 }

</style>
</head>

<%= form_for(@user) do |f| %>
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <body>
  <div class="header">

    

  <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), users_path%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div> <!--end signup-->

</div>
  <div class="container">
  </div>
  <div id="burlap">
  <div class="form">
    <div id="title1">
   <h1> Sign Up </h1>
    </div>
<form class="well">
  <div class="field">
    <%= f.text_field :name, :placeholder =>"name" %>
  </div>
  <div class="field">
    <%= f.text_field :email, :placeholder =>"email" %>
  </div>
  <div class="field">
    <%= f.password_field :password, :placeholder =>"password" %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :placeholder =>"confirm your password" %>
  </div>
  <div class="field">
    <%= f.text_area :description, :placeholder =>"tell us a little bit about yourself","cols" => 20, "rows" => 30 %>
  </div>
  
  </form>

 
  <div class="actions">
    <%= f.submit class: 'btn-large btn-inverse' %>
  </div>
</div>
</div>
  <div id="main">
  <div id="credits"></div>
</div>

</body>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'edit' %>

app/views/users/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Steep - An App for All Things Tea</title>
<link rel="stylesheet" type="text/css" href="/assets/users.css.erb" />
<style type="text/css">
#login {
	position:absolute;
	width:278px;
	height:217px;
	z-index:1;
	left: 1274px;
	top: -6px;
}
#signup {
	position:absolute;
	width:216px;
	height:244px;
	z-index:2;
	left: 1415px;
	top: -14px;
}
#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#paperbox {
  position:absolute;
  background: url(<%= asset_path 'paperbox.png' %>) no-repeat scroll 0 0;
	width:784px;
	height:567px;
	z-index:4;
	left: 500px;
	top: -200px;
}	
#credits {
	position:absolute;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}
#txt{
  position:absolute;
  left:80px;
  top:60px;
  height:400px;
  width:600px;
  z-index:5;
  overflow:auto;
}

#home {
  position:absolute;
  top:20px;
  left:20px;
}

</style>
</head>

<body>
<div id="teasliked"></div>
<div id="typesliked"></div>
<!--<img src="images/background.png" width="4800" height="3600" />-->
<div class="header">

    

<% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>

</div><!--end class header"-->
<div class="container">

</div><!--end class container-->
<div id="username"></div>
<div id="profilepic"></div>
<div id="main">
  <div id="paperbox">  <div id = "txt">  
    

<h1>Users</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Image</th>
    <th>Tea</th>
    <th>Teatype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= thumbnail_for user %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.image %></td>
    <td><%= link_to 'View Profile Page', user %></td>
    
  </tr>
<% end %>
</table>

<br />
</div>
</div>
    
  <div id="credits"></div>
</div>

<div id="home">
    <%= link_to image_tag("/assets/hometab.png", :border=>0), root_path%>
  
  </div>
</body>
</html>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Steep - An App for All Things Tea</title>

<style type="text/css">


body {
    font-family: PTSansRegular;
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-size: 100%;
    line-height: 1;
}

body {
	background-attachment: scroll;
	background-color: #FC9;
	background-image: url(<%= asset_path 'bg1920x1080.png' %>);
	background-repeat: no-repeat;
	background-position: fixed;
}

.header {
	width: 1920px;
	height: 360px;
}


.container {
    width: 1920px;
	height: auto;
} 

#username {
	background: url(<%= asset_path 'username.png' %>) no-repeat scroll 0 0;
}

#profilepic {
	background: url(<%= asset_path 'profilepic.png' %>) no-repeat scroll 0 0;
}

#teasliked {
	background: url(<%= asset_path 'teasliked3.png' %>) no-repeat scroll 0 0;
}

#typesliked {
	background: url(<%= asset_path 'typesliked.png' %>) no-repeat scroll 0 0;
}

#credits {
	background: url(<%= asset_path 'credits.png' %>) no-repeat scroll 0 0;
}	
#login {
	position:absolute;
	width:278px;
	height:217px;
	z-index:1;
	left: 1274px;
	top: -6px;
}
#signup {
	position:absolute;
	width:216px;
	height:244px;
	z-index:2;
	left: 1415px;
	top: -14px;
}
#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#credits {
	position:absolute;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}
#username {
	position:absolute;
	width:400px;
	height:127px;
	z-index:4;
	left: 221px;
	top: 31px;
}
#actualname {
  position:absolute;
	width:400px;
	height:127px;
	z-index:5;
	left: 0px;
	top: 40px;
  text-align: center;
}
#profilepic {
	position:absolute;
	width:411px;
	height:417px;
	z-index:5;
	left: 211px;
	top: 166px;
}
#actualpic {
	position:absolute;
	width:411px;
	height:417px;
	z-index:6;
	left: 40px;
	top: 40px;
}
#description {
  background: url(<%= asset_path 'description.png' %>) no-repeat scroll 0 0;
  position:absolute;
	width:411px;
	height:417px;
	z-index:6;
	left: 211px;
	top: 575px;
}

#descriptionscroller {
 position:absolute;
	width:340px;
	height:150px;
	z-index:7;
	left:22px;
	top: 22px;
  overflow:auto;
}
#teasliked {
	position:absolute;
	width:511px;
	height:371px;
	z-index:6;
	left: 666px;
	top: 27px;
}

#teaslikedscroll {
  position:absolute;
  left:50px;
  top:80px;
  width:400px;
  height:240px;
  z-index:10;
  overflow:auto;

  
}
#comments{
  background: url(<%= asset_path 'comments.png' %>) no-repeat scroll 0 0;
  position:absolute;
	width:602px;
	height:355px;
	z-index:8;
	left: 664px;
	top: 422px;
}
#wall{
  position:absolute;
  width:400px;
  height:355px;
  z-index:9;
  left:700px;
  top:450px;
}
#actualwall{
  position:absolute;
  width:430px;
  height:270px;
  z-index:10;

  overflow:auto;
}
#wallposter{
  background: url(<%= asset_path 'commentbox.png' %>) no-repeat scroll 0 0;
  position:absolute;
  width:602px;
  height:250px;
  z-index:9;
  left:664px;
  top:800px;
  
}
#commentboxes {
  position:absolute;
  left:40px;
  top:20px;
}
textarea#post_area {
  width:400px;
  height:50px;
}

#recommend {
  background: url(<%= asset_path 'commentbox.png' %>) no-repeat scroll 0 0;
  position:absolute;
  width:602px;
  height:250px;
  z-index:9;
  left:164px;
  top:800px;
}

#recommendtext{
  position:absolute;
  width:502px;
  height:100px;
  z-index:9;
  top:50px; 
  text-align:center;
}
#editbutton {
  position:absolute;
  width:502px;
  height:250px;
  z-index:9;
  top:90px;
  left:235px;
}

#deletebutton {
  position:absolute;
  width:502px;
  height:250px;
  z-index:9;
  top:90px;
  left:270px;
}

#changeimage {
  position:absolute;
  width:502px;
  height:250px;
  z-index:9;
  top:90px;
  left:130px;
}

#home {
  position:absolute;
  top:20px;
  left:20px;
}

</style>
</head>

<body>
<div id="teasliked">
  <div id="teaslikedscroll">
    <% @user.teas.uniq.each do |tea| %>
  <h3><%= tea.name %></h3>
<%end%>
</div>
  
  
</div>
<!--<img src="images/background.png" width="4800" height="3600" />-->
  <div class="header">

    
    <% if signed_in? %>
      <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

   <%else%>
     <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

   <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div><!--end class header-->
<div class="container">

</div><!--end class container-->
<%provide(:title, @user.name)%>
  <div id="username">
   <div id="actualname">
    <h1><%= @user.name %></h1>
   </div>
   <% if signed_in? %>
   <% if @user == current_user%>
     <div id="editbutton">
       <%= link_to "Edit", edit_user_path(@user) %>
      </div>
     <div id ="deletebutton">
       <%= link_to 'Delete User', current_user, confirm: 'Are you sure?', method: :delete %></td>
      </div>
      <div id = "changeimage">
        <%= link_to "Change Image", href = "https://en.gravatar.com/site/login/%2Fsite%2Fsignup%2F" %>
       </div>
     <%end%>
  <%end%>
</div>

<div id="profilepic">
  <div id = "actualpic">
    <%= gravatar_for @user %>
 </div>
</div>

<div id="description">
  <div id="descriptionscroller">
  <%= @user.description %>
  </div>
</div>

<div id="comments"></div>

<div id="wall">
  <h2>Wall</h2>
  <div id="actualwall">

    <table>
    <% @user.posts.each do |post| %>
    <h3><%= post.title %></h3>
    <div><%= post.post %></div>
    </br> 
     <% end %>
    </table>
  </div>
  </div>
</div>

<% if signed_in? %>
  <div id="wallposter">
   <div id="commentboxes">
  
  <%= form_for(@post) do |f| %>
  <%= f.hidden_field :user_id%>
  <div id="posttitle">

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="field">
    <%= f.label :post %>
    <%= f.text_area :post, :id => "post_area" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>
<%end%>

 <% if signed_in? %>
  <% if @user == current_user%>
  <div id="recommend">
    <div id="recommendtext">
      <h1>Recommended for you!</h1>
     <p id="notice"><%= notice %></p>
    <div id="recommendation">
      <%if (@rand != nil)%>
       <h2><%= @rtea.name %> </h2>
     <%end%>
  <%end%>

<%end%>
</div>
</div>
</div>

<div id="main">
  <div id="credits"></div>
</div>

  <div id="home">
    <%= link_to image_tag("/assets/hometab.png", :border=>0), root_path%>
  
  </div>
</body>
</html>