config/routes.rb
Steep::Application.routes.draw do

  resources :posts

  
  resources :teas do
    get 'search'
    resources :likes
  end

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :users do
    resources :posts
  end 
  
  resources :tea_types do
  end
  match '/teas/search' => 'teas#search', :as => "search"
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/auth/:provider/callback" => "sessions#new"  

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Steep - An App for All Things Tea</title>
<link rel="stylesheet" type="text/css" href="/assets/home.css.erb" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>
function toggleTab(thechosenone) {
      var search = document.getElementsByTagName("div");
            for(var x=0; x<search.length; x++) {
                  name = search[x].getAttribute("name");
                  if (name == 'search') {
                        if (search[x].id == thechosenone) {
                        search[x].style.display = 'block';
                  }
                  else {
                        search[x].style.display = 'none';
                  }
            }
      }
}
</script>

<style type="text/css">
#login {
	position:absolute;
	width:278px;
	height:329px;
	z-index:1;
	left: 1274px;
	top: 16px;
}
#signup {
	position:absolute;
	width:216px;
	height:323px;
	z-index:2;
	left: 1415px;
	top: 8px;
}
#main {
	position:absolute;
	width:1882px;
	height:425px;
	z-index:3;
	left: 16px;
	top: 366px;
}
#teas {
	position:absolute;
	width:1676px;
	height:380px;
	z-index:1;
	left: 120px;
	top: 0px;
}
#black {
	position:absolute;
	width:280px;
	height:380px;
	z-index:1;
	left: 214px;
	top: 0px;
}
#green {
	position:absolute;
	width:280px;
	height:380px;
	z-index:2;
	left: 464px;
	top: 0px;
}
#white {
	position:absolute;
	width:280px;
	height:380px;
	z-index:3;
	left: 717px;
	top: 0px;
}
#yellow {
	position:absolute;
	width:280px;
	height:380px;
	z-index:4;
	left: 969px;
	top: 0px;
}
#oolong {
	position:absolute;
	width:280px;
	height:280px;
	z-index:5;
	left: 1222px;
	top: 0px;
}
#credits {
	position:absolute;
	width:252px;
	height:185px;
	z-index:2;
	left: -41px;
	top: 256px;
}
#searchusers {
  display:none;
}
</style>
</head>

<body>
<!--<img src="app/assets/images/background.png" width="4800" height="3600" />-->
<div class="header">
  <div class="search-choices">
    <a href="javascript:toggleTab('searchteas');"> Search Teas </a>
    <a href="javascript:toggleTab('searchusers');"> Search Users </a>
  </div>
  <div name="search" id="searchteas">
      <%= form_tag search_path, :method => 'get' do%>
  <p>
      <%= text_field_tag :search, params[:search], :placeholder =>"search teas"%>
      <%= submit_tag "Search", :name => nil %>
  </p>
  <%end%>
</div>
  <div name="search" id="searchusers">
      <%= form_tag users_path, :method => 'get' do%>
  <p>
      <%= text_field_tag :search, params[:search], :placeholder =>"search users"%>
      <%= submit_tag "Search", :name => nil %>
  </p>
  <%end%>
  </div>
  
  <div id="titleh">
  </div> <!--end title-->
    
  <% if signed_in? %>
  <div id="login"><%= link_to image_tag("/assets/logout.png", :border=>0), signout_path, method: "delete"%></div> 
    <!--end login-->
        
  <div id="signup"><%= link_to image_tag("/assets/profile.png", :border=>0), user_path(current_user)%></div> <!--end signup-->

  <%else%>
    <div id="login"><%= link_to image_tag("/assets/logintab.png", :border=>0), signin_path%></div> 

    <!--end login-->
        
    <div id="signup"><%= link_to image_tag("/assets/signuptab.png", :border=>0), new_user_path%></div>  <!--end signup-->
  <%end%>
</div><!--end class header"-->
<div class="container">

</div><!--end class container-->
<div id="main">
  <div id="teas">
    <div id="black"><%= link_to image_tag("/assets/black.png", :border=>0), tea_type_path(:id => 1) %></div>
    <div id="green"><%= link_to image_tag("/assets/green.png", :border=>0),tea_type_path(:id =>4) %></div>
    <div id="white"><%= link_to image_tag("/assets/white.png", :border=>0), tea_type_path(:id =>3) %></div>
    <div id="yellow"><%= link_to image_tag("/assets/yellow.png", :border=>0), tea_type_path(:id =>5) %></div>
    <div id="oolong"><%= link_to image_tag("/assets/oolong.png", :border=>0), tea_type_path(:id =>2) %>
				<!--<img src="/assets/oolong.png" alt="Oolong Teas"/></a>--></div> 
  </div>
  <div id="credits"></div>
</div>


</body>
</html>